version: '3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./public:/app/public
      - ./.env:/app/.env
    environment:
      - NODE_ENV=development
    command: >
      sh -c "npm run build && npm start"