[build]
  # Skip the npm build command entirely since we don't need it
  command = "echo 'No build step required for static files'"
  publish = "public"
  functions = "netlify/functions"

# Redirect API requests to serverless functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Fallback for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200